stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    params:
    - make_dataset.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed
    - src/features/build_features.py
    params:
    - build_features.max_features
    outs:
    - data/features
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    params:
    - train_model.learning_rate
    - train_model.n_estimators
    outs:
    - model.pkl
  predict_model:
    cmd: python src/models/predict_model.py
    deps:
    - model.pkl
    - src/models/predict_model.py
    metrics:
    - metrics.json
